# Generated by Django 5.2.1 on 2025-06-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phase",
            name="order",
        ),
    ]
