# Generated by Django 5.2.1 on 2025-06-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_phase_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectgallery",
            options={},
        ),
        migrations.RemoveField(
            model_name="projectgallery",
            name="order",
        ),
        migrations.AddField(
            model_name="phase",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
